# Generated by Django 3.0.8 on 2020-07-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmate_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_sex',
            new_name='sex',
        ),
    ]
