# Generated by Django 3.0.8 on 2020-08-04 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmate_app', '0002_auto_20200728_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendshipRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_status', models.CharField(choices=[('friend', 'friend'), ('unrelated', 'unrelated'), ('ignored', 'ignored')], max_length=10)),
                ('relation_date', models.DateTimeField(verbose_name='relation_creation_date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_sender', to=settings.AUTH_USER_MODEL)),
                ('user_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
