# Generated by Django 3.0.8 on 2020-08-06 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmate_app', '0003_friendshiprelations'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersInvitations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_status', models.CharField(choices=[('confirmed', 'confirmed'), ('rejected', 'rejected'), ('waiting', 'waiting')], max_length=10)),
                ('relation_date', models.DateTimeField(verbose_name='relation_creation_date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invitation_sent', to=settings.AUTH_USER_MODEL)),
                ('user_invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invitation_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
